### ISSUE TITLE
Loading Metacello in Squeak loads an old version of WebClient

### ISSUE THREAD

**Issue by j4yk** [Metacello/metacello#438]
When loading Metacello into a fresh Squeak trunk image, a version of WebClient that is not up-to-date with the trunk is loaded. I assume this is because the Metacello baseline references another repository to fetch WebClient from. That repository does not contain the latest versions present in the Squeak trunk repository.

```
 "..."
 spec
    for: #'squeak'
    do: [ 
      "..."
      spec
        package: 'WebClient-Core'
        with: [ spec repository: 'http://ss3.gemstone.com/ss/WebClient' ].
      "..."
```

This may cause bugs in other, subsequently loaded software that depends on the newer WebClient versions. Workaround is to invoke the Squeak update again after installing Metacello.

**Comment by krono** [comment]
I always wanted to fix that.
Also, maybe this should be a `#project:` and Squeak should just "provide" this project…
