### ISSUE TITLE
MetaceloPackageSpec workingCopyNameFor call name which could lead to deprecation warning when current version is array in Pharo

### ISSUE THREAD

**Issue by jecisc** [Metacello/metacello#446]
I think that Pharo will soon want to sync with this repo. Since there was changes to the Pharo Metacello I'll try to port some of the changes here to make the sync easier. 

This issue correspond to pharo issue: https://pharo.fogbugz.com/f/cases/18867

This is caused by the fact that Object>>name was removed of Pharo

Opened by Denis Kudryashov 08/04/2016 2:51 PM
Sometimes when I load configuration by Gofer I got "Object name" deprecation warning. It caused by "MetaceloPackageSpec workingCopyNameFor:" when current version info is array (somehow or maybe always)

**Comment by dalehenrich** [comment]
This bug fixed by @estebanlm ... [see this comment](https://github.com/Metacello/metacello/pull/447#issuecomment-333678766)
