### ISSUE TITLE
Wrong repository spec is not detected, HTTP 404 not caught

### ISSUE THREAD

**Issue by j4yk** [Metacello/metacello#477]
Today I tried to load a branch of a Squeak project of mine via Metacello without first pushing that branch. Stupid me. So my `Metacello new repository: 'http://github.com/...'` pointed to a non-existent branch. When downloading the zipball in MetacelloSqueakPlatform>>#downloadZipArchive:to:, a 404 response is received, but it is not checked whether the request was actually successful. The response is unconditionally streamed to the target file, which gives me a zip file containing the text "404: Not Found". Of course, this cannot be understood by ZipArchive later on in that method, so `archive readFrom: fileStream` yields a "file too short" error.

This error is subsequently caught in MetacelloCommonMCSpecLoader>>#retryingResolvePackageSpecReferences:gofer:, so eventually you get a debugger complaining "baseline could not be resolved". Thus, the actual problem (the wrong repository url) is quite obfuscated (until you restart, properly step through, inspect the stack when the error is repeated and look at the proper variables -- or until you look at the downloaded zip file with your favorite text editor).

**Comment by dalehenrich** [comment]
Okay ... the GemStone code base [raises an error indicating that the zip download failed and pointer to the possible problem](https://github.com/Metacello/metacello/blob/master/repository/Metacello-Platform.gemstone.package/MetacelloGemStonePlatform.class/instance/downloadZipArchive.to..st#L13-L28), however as you point out the Squeak implementation uses [WebClient to download the zip file](https://github.com/Metacello/metacello/blob/master/repository/Metacello-Platform.squeak.package/MetacelloSqueakPlatform.class/instance/downloadZipArchive.to..st#L6) and I'm not familiar enough with WebClient to supply a better solution.

**Comment by dalehenrich** [comment]
@krono would you be able to implement a solution?

**Comment by krono** [comment]
thanks
