### ISSUE TITLE
Error while using Semantic versionning with TravisCI

### ISSUE THREAD

**Issue by jecisc** [Metacello/metacello#495]
I tried to reference a Seaside version in a baseline using semantic versioning like this:

```Smalltalk
spec
		baseline: 'Seaside3'
		with: [ spec
				loads: #('Core' 'JQuery' 'Zinc');
				repository: 'github://SeasideSt/Seaside:3.2.?/repository' ]
```

The problem is that all my checks from TravisCI end up in failure with this error:

```
MCRepositoryError: Error accessing tags for github project: 'SeasideSt/Seaside' -> 'API rate limit exceeded for 34.233.56.198. (But here''s the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)'
```

I wonder if the number of requests could be reduced...

**Comment by pdebruic** [comment]
Or the requests authenticated?

**Comment by dalehenrich** [comment]
I think that authentication would only apply to individual users on their own machine ...

**Comment by pdebruic** [comment]
Once you get a no-scope token from

https://github.com/settings/tokens

You can configure Monticello to use it to access github by running

MCGitHubRepository siteUsername: 'myUsername' sitePassword: 'token'

**Comment by jecisc** [comment]
I found that also: https://developer.github.com/v3/#conditional-requests

I don't have time to look much on it but maybe it can be used for tags.

**Comment by dalehenrich** [comment]
GemStone is now using the conditional requests FWIW ...
