### ISSUE TITLE
Error when installing on Squeak 5.1: Could not resolve: ConfigurationOfMetacelloPreview

### ISSUE THREAD

**Issue by dubst3pp4** [Metacello/metacello#496]
When I'm trying to install Metacello using your instructions in an Squeak 5.1 image, I get the following error while doing the third step:

Workspace:
```
"Load the Preview version of Metacello from GitHub"
(Smalltalk at: #Metacello) new
  configuration: 'MetacelloPreview';
  version: #stable;
  repository: 'github://Metacello/metacello:configuration';
  load.
```
The Debugger opens with the title 

`Could not resolve: ConfigurationOfMetacelloPreview` 

and the stack trace:
```
MetacelloFetchingMCSpecLoader>>retryingResolvePackageSpecReferences:gofer:
[...]
```
Any ideas?

**Comment by krono** [comment]
Hi Marc. This is a bug in WebClient. as I told @ckeen (https://toot.berlin/@krono/100748602301266391), Please load the latest WebClient from Trunk :)
