### ISSUE TITLE
[Merge Request for Gofer] Gofer-Core.squeak-ct.136

### ISSUE THREAD

**Issue by LinqLover** [Metacello/metacello#555]
# [Gofer-Core.squeak-ct.136.mcz](https://github.com/Metacello/metacello/files/9564619/Gofer-Core.squeak-ct.136.mcz.zip)

I'd like to request to merge this patch into http://seaside.gemtalksystems.com/ss/metacello, but I don't have write access to it. @dalehenrich or anyone else with write access, would you mind reviewing & merging this? Thanks in advance!

See also: <https://lists.squeakfoundation.org/pipermail/squeak-dev/2021-June/215918.html>

---

> ==================== Summary ====================
> 
> Name: Gofer-Core.squeak-ct.136
> Author: ct
> Time: 14 September 2022, 11:04:24.862009 am
> UUID: 125a7550-6d87-ff45-9717-3ae4694acda0
> Ancestors: Gofer-Core.squeak-dkh.135
> 
> Updates extension method SystemOrganizer>>#environment to complement System-tonyg.1224 for Squeak. If the environment variable is not available, the code will still compile with a nil literal for environment, falling back to the prior logic. Marks the method as proper override.
> 
> =============== Diff against Gofer-Core.squeak-dkh.135 ===============
> 
> SystemOrganizer>>environment {*Gofer-Core-accessing-override} · ct 9/14/2022 11:01 (changed and categorized)
> ```diff
> environment
> - 
> - 	^Smalltalk
> + 	^ environment ifNil: [Smalltalk]
> ```

**Comment by dalehenrich** [comment]
@LinqLover if you register as a member of [GemSource](http://seaside.gemtalksystems.com/ss) and provide me with your username, I will add you as a project admin for the [Metacello project](http://seaside.gemtalksystems.com/ss/metacello.html) which will allow you to manage any future issues that may arise ... I assume that an alternate solution would be to reference a different repository for that package, but I haven't looked at the issue in detail and I know that bootstrapping Metacello into an image without Filetree can be a challenge :smile:

**Comment by LinqLover** [comment]
I have just registered as `ct` on GemSource. :-)

**Comment by dalehenrich** [comment]
Okay and I've added you as admin to the [Metacello project](http://seaside.gemtalksystems.com/ss/metacello.html) ...

**Comment by LinqLover** [comment]
[Gofer-Core.squeak-ct.136.mcz](http://seaside.gemtalksystems.com/ss/metacello/Gofer-Core.squeak-ct.136.mcz) is up, but `ConfigurationOfGofer` still refers to Gofer-Core.squeak-dkh.135 ... Should I just update the reference in all 1.0.5 versions for Squeak?

![image](https://user-images.githubusercontent.com/38782922/190377652-f6088e18-fd86-42f7-afc5-bb6866448de0.png)

**Comment by dalehenrich** [comment]
Yes... that makes sense ..

**Comment by LinqLover** [comment]
Alright, now it works! Thank you :-)
